### ISSUE TITLE
CP3 Review.

### ISSUE THREAD

**Issue by jobala** [andela-mkwamboka/dms#1]
- What happens when someone gets or deletes a role that does not exist?
- `expect(res.status).to.equal(200);
      expect(res.body).to.be.a('object');
      expect(res.body).to.have.all.keys('message', 'token')`
  Assert the actual values of the message/token
- Remove commented code
- Rename your controllers by removing ctrl, they are already in the controllers directory

**Comment by monicaah** [comment]
Thanks for the feedback Japheth
